### ISSUE TITLE
您好可以详细一下如何使用吗 

### ISSUE THREAD

**Issue by puppyK** [stay-leave/enhance_llm#1]
用bolg程序 跑了一下 填入了cookie 换了关键词 
报错如下
Traceback (most recent call last):

  File "D:\pachong\weibo-crawler-main\weibo_blog.py", line 8, in <module>
    from fake_useragent import UserAgent  # 随机请求头

ModuleNotFoundError: No module named 'fake_useragent'

**Comment by stay-leave** [comment]
安装这个库就行

**Comment by puppyK** [comment]
> 安装这个库就行

您好 库的名称是什么 fake_useragent提示找不到 我用的annoconda
