### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by zjuermath** [stay-leave/enhance_llm#11]
请问可以给出embedding微调部分的依赖包吗，好像项目中没有

**Comment by stay-leave** [comment]
真没了，晚上我找找。也可以自己根据llama_index配

**Comment by stay-leave** [comment]
已上传

**Comment by zjuermath** [comment]
感谢感谢



---Original---
From: ***@***.***&gt;
Date: Thu, Jun 20, 2024 21:03 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [stay-leave/enhance_llm] requirements.txt (Issue #11)




 
已上传
