### ISSUE TITLE
请问为啥我想试用下微博的爬虫，点击最新链接跳转到大模型项目去了，爬虫三件套项目取消了吗

### ISSUE THREAD

**Issue by Decade-rider** [stay-leave/enhance_llm#12]

**Comment by Decade-rider** [comment]
> _未提供说明。_

https://github.com/stay-leave/weibo-crawler就是这个项目

**Comment by stay-leave** [comment]
白嫖的不说，有些还理直气壮地问着问那。现在变成付费的了，需要通过公众号联系我

**Comment by Decade-rider** [comment]
好的，那很冒昧的问下，weibo-public-opinion-analysis这个项目里面的代码还能用吗，打扰您了






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月20日(星期四) 晚上9:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [stay-leave/enhance_llm] 请问为啥我想试用下微博的爬虫，点击最新链接跳转到大模型项目去了，爬虫三件套项目取消了吗 (Issue #12)














 
白嫖的不说，有些还理直气壮地问着问那。现在变成付费的了，需要通过公众号联系我

**Comment by stay-leave** [comment]
能用。是基于cn手机端爬取的，字段少点，做简单研究足够了

**Comment by Decade-rider** [comment]
请问支持爬取二级评论吗，我主要是爬取个100条左右看看大概讨论内容，爬虫的话我有过作为课程作业爬过京东的评论，不知道这个难度大不大，又觉得现成的八爪鱼、后裔采集器不太好用，哈哈哈哈哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月20日(星期四) 晚上9:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [stay-leave/enhance_llm] 请问为啥我想试用下微博的爬虫，点击最新链接跳转到大模型项目去了，爬虫三件套项目取消了吗 (Issue #12)














 
能用。是基于cn手机端爬取的，字段少点，做简单研究足够了

**Comment by stay-leave** [comment]
付费版支持

**Comment by Decade-rider** [comment]
好的，谢谢您的解答，还有最后一个问题，就是这个项目weibo-public-opinion-analysis一般只需要更改cooki就行了是吗，我对于爬虫说实话了解的也不是很多




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月20日(星期四) 晚上9:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [stay-leave/enhance_llm] 请问为啥我想试用下微博的爬虫，点击最新链接跳转到大模型项目去了，爬虫三件套项目取消了吗 (Issue #12)














 
付费版支持

**Comment by stay-leave** [comment]
是，不行就把请求头都更新
