### ISSUE TITLE
评论爬虫程序使用问题

### ISSUE THREAD

**Issue by puppyK** [stay-leave/enhance_llm#2]
您好 我是程序小白 我在完成关键词爬虫之后 想继续使用评论爬虫 修改路径添加cookie之后出现如下错误
Excel xlsx file; not supported
我根据一些网上的方法安装了旧版（1.2.0）xlrd，出现了以下错误
'ElementTree' object has no attribute 'getiterator'

可以怎么解决一下呢

**Comment by stay-leave** [comment]
我的也是1.2.0版本，你打开的是xlsx文件吗？或者你重启下编辑器

**Comment by stay-leave** [comment]
如果有相关的科研需要可以在csdn私信我
