### ISSUE TITLE
程序运行问题

### ISSUE THREAD

**Issue by naniko7** [stay-leave/enhance_llm#3]
hi，个人对爬虫第一次接触不太熟悉，有几个问题想要询问：
1.该程序是否需要自身先收集微博正文xlsx文件？如果需要，这部分数据的来源收集方式是？
2.爬虫部分的脚本执行步骤，我应当先执行哪个脚本呢？脚本之间是否有关联（比如脚本一需要生成文件，该文件将传入脚本二）

感谢查看与回答。

**Comment by stay-leave** [comment]
1.微博正文获取需要使用weibo_blog.py，键入关键词即可。
2.顺序是先获取微博正文，然后根据正文文件获取评论，需要评论爬虫可csdn私信我，然后根据评论文件获取用户信息（或者直接输入用户id也可以）
