### ISSUE TITLE
weibo_blog使用情况反馈

### ISSUE THREAD

**Issue by yitacls** [stay-leave/enhance_llm#4]
作者您好，我在使用weibo_blog发现了一些需要补充的地方：
1.报错：UnboundLocalError: local variable 'XXX' referenced before assignment
解决：部分代码没有对齐，如第159~162行，导致循环外使用循环内定义变量，所以需要增加缩进
2.文件保存前需要在weibo-crawler-main目录下创建'微博正文'文件夹
3.soup.select函数路径与我使用的微博网页不匹配，导致爬取内容缺失，所以对相关代码进行了修改
![image](https://user-images.githubusercontent.com/75364857/211182967-4768e37c-3987-479e-8e96-12f64d783a71.png)

**Comment by stay-leave** [comment]
非常感谢您的修改，也欢迎您把修改后的代码发到这个项目上，如果方便的话。
你的网页是https://weibo.com/吗？我的是针对这个站点进行爬取的。如果也是这个站点，那应该是微博更新了源码架构。

**Comment by yitacls** [comment]
我已经将修改后的代码进行了上传，但并没有删除掉注释，您可以进行测试后删去或修改。
我爬取的搜索页面是https://s.weibo.com/。

**Comment by stay-leave** [comment]
非常感谢您的修改！
网站是一样的，是微博改了网页结构。
